#@TYPE: Machine
#@NAME: Nvidia Jetson Orin NX 16GB (P3767-0000)
#@DESCRIPTION: Nvidia Jetson Orin NX module in P3768 carrier

DEFAULTTUNE ??= "armv8a-crc"
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     '', 'conf/machine/include/arm/arch-armv8-2a.inc', d)}
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     'conf/machine/include/orin-nx.inc', '', d)}
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     'conf/machine/include/devkit-wifi.inc', '', d)}

MACHINE_FEATURES ??= "alsa usbhost pci rtc ext2"

KERNEL_IMAGETYPE ?= "Image"

SERIAL_CONSOLES ??= "115200;ttyTCU0"

KERNEL_DEVICETREE ??= "tegra234-p3768-0000+p3767-0000-nv-super.dtb"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_VERSION_linux-yocto ?= "6.12%"
PREFERRED_VERSION_linux-yocto-rt ?= "6.12%"

MACHINE_EXTRA_RRECOMMENDS:append = " kernel-modules"
IMAGE_FSTYPES += "tar.bz2 ext4"
IMAGE_INSTALL:append = " kernel-image-image"

MACHINEOVERRIDES:append = ":nvidia-orin"

# If enable reduntant flash layout, L4TConfiguration-RootfsRedundancyLevelABEnable.dtbo will be installed
USE_REDUNDANT_FLASH_LAYOUT_DEFAULT ?= "0"

BSP_NVIDIA_DERIVED:append=" nvidia-orin-nx"

TEGRA_PLUGIN_MANAGER_OVERLAYS:append = " ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
	'tegra234-p3767-camera-p3768-imx219-dual.dtbo', '', d)}"

ASSUME_PROVIDED += "virtual/bootloader"
OSTREE_SD_UBOOT_WIC1 = ""
