#@TYPE: Machine
#@NAME: Nvidia Jetson AGX Orin 64GB
#@DESCRIPTION: Nvidia Jetson Orin dev kit (P3701-0005 module in P3737-0000 carrier)

DEFAULTTUNE ??= "armv8a-crc"
TEGRA_BOARDSKU ?= "0005"
TEGRA_BUPGEN_SPECS ?= "fab=300;boardsku=0005;boardrev=;chipsku=00:00:00:D0;bup_type=bl \
                       fab=300;boardsku=0005;boardrev=;bup_type=kernel"
TEGRA_FLASHVAR_BPFDTB_FILE ?= "tegra234-bpmp-3701-0005-3737-0000.dtb"
TEGRA_FLASHVAR_PMIC_CONFIG ?= "tegra234-mb1-bct-pmic-p3701-0005.dts"
TEGRA_FLASHVAR_WB0SDRAM_BCT ?= "tegra234-p3701-0005-wb0sdram-l4t.dts"

EMMC_BCT ?= "tegra234-p3701-0005-sdram-l4t.dts"
ROOTFSPART_SIZE_DEFAULT ?= "59055800320"

require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     '', 'conf/machine/include/arm/arch-armv8-2a.inc', d)}
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     'conf/machine/include/agx-orin.inc', '', d)}
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     'conf/machine/include/devkit-wifi.inc', '', d)}

MACHINE_FEATURES ??= "alsa usbhost pci rtc ext2"

KERNEL_IMAGETYPE ?= "Image"

SERIAL_CONSOLES ??= "115200;ttyTCU0"

KERNEL_DEVICETREE = "${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
	'tegra234-p3737-0000+p3701-0005-nv.dtb', 'tegra234-p3737-0000+p3701-0000.dtb', d)}"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_VERSION_linux-yocto ?= "6.12%"
PREFERRED_VERSION_linux-yocto-rt ?= "6.12%"

MACHINE_EXTRA_RRECOMMENDS:append = " kernel-modules"
IMAGE_FSTYPES += "tar.bz2 ext4"
IMAGE_INSTALL:append = " kernel-image-image"

MACHINEOVERRIDES:append = ":nvidia-orin"

# If enable reduntant flash layout, L4TConfiguration-RootfsRedundancyLevelABEnable.dtbo will be installed
USE_REDUNDANT_FLASH_LAYOUT_DEFAULT ?= "1"

BSP_NVIDIA_DERIVED:append=" nvidia-orin-agx"

TEGRA_PLUGIN_MANAGER_OVERLAYS:append = " ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
	'tegra234-p3737-camera-imx477-overlay.dtbo', '', d)}"
