#@TYPE: Machine
#@NAME: Nvidia Jetson Orin Nano 8GB (P3767-0003)
#@DESCRIPTION: Nvidia Jetson Orin dev kit (P3767-0003 module in P3768-0000 carrier)

DEFAULTTUNE ??= "armv8a-crc"

TNSPEC_BOOTDEV ?= "nvme0n1p1"
PARTITION_LAYOUT_TEMPLATE_DEFAULT ?= "flash_t234_qspi.xml"
PARTITION_LAYOUT_TEMPLATE_DEFAULT_SUPPORTS_REDUNDANT ?= "1"
PARTITION_LAYOUT_EXTERNAL_DEFAULT ?= "flash_l4t_t234_nvme.xml"

TEGRAFLASH_SDCARD_SIZE ?= "64G"
ROOTFSPART_SIZE_DEFAULT ?= "59055800320"

KERNEL_DEVICETREE ?= "tegra234-p3768-0000+p3767-0005-nv-super.dtb"

require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     '', 'conf/machine/include/arm/arch-armv8-2a.inc', d)}
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     'conf/machine/include/orin-nano.inc', '', d)}
require ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
			     'conf/machine/include/devkit-wifi.inc', '', d)}

MACHINE_FEATURES ??= "alsa usbhost pci rtc ext2"

KERNEL_IMAGETYPE ?= "Image"

SERIAL_CONSOLES ??= "115200;ttyTCU0"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_VERSION_linux-yocto ?= "6.12%"
PREFERRED_VERSION_linux-yocto-rt ?= "6.12%"

MACHINE_EXTRA_RRECOMMENDS:append = " kernel-modules"
IMAGE_FSTYPES += "tar.bz2"
IMAGE_INSTALL:append = " kernel-image-image"

MACHINEOVERRIDES:append = ":nvidia-orin:jetson-orin-nano-devkit"

# If enable reduntant flash layout, L4TConfiguration-RootfsRedundancyLevelABEnable.dtbo will be installed
USE_REDUNDANT_FLASH_LAYOUT_DEFAULT ?= "1"

BSP_NVIDIA_DERIVED:append=" nvidia-orin-nano"

TEGRA_PLUGIN_MANAGER_OVERLAYS:append = " ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
	'tegra234-p3767-camera-p3768-imx219-dual.dtbo', '', d)}"

BOOTABLE_OVERLAY ?= "tegra234-p3768-0000+p3767-0005-nv-super-boot-overlay.dtbo"

ASSUME_PROVIDED += "virtual/bootloader"
OSTREE_SD_UBOOT_WIC1 = ""
