#@TYPE: Machine
#@NAME: Nvidia Jetson Orin AGX
#@DESCRIPTION: Nvidia Jetson Orin AGX dev board

# Add meta-tegra machine configuration
require conf/machine/include/agx-orin.inc
require conf/machine/include/devkit-wifi.inc

TEGRA_BUPGEN_SPECS ?= "fab=300;boardsku=0000;boardrev=;chipsku=00:00:00:D0;bup_type=bl \
                       fab=300;boardsku=0000;boardrev=;bup_type=kernel"

# Force to use the prebuilt UEFI binaries
PREFERRED_PROVIDER_virtual/bootloader = "tegra-uefi-prebuilt"

# Force tegra-common.inc to use prebuit optee binaries
USE_PREBUILT_OPTEE = "1"

# Force tegra-common.inc to generate a /boot/extlinux/extlinux.conf
# including l4t-launcher-extlinux.bb as UEFI won't work if not used this
UBOOT_EXTLINUX = "1"

# Set kernel to custom WRL one
PREFERRED_PROVIDER_virtual/kernel ??= "linux-yocto"

# Both LTS22 wrlinux/recipes-devtools/gcc8/gcc-8-cross and
# meta-tegra meta-tegra/recipes-devtools/gcc-for-nvcc
# provide gcc-8-cross-aarch64, so select the one from meta-tegra
PREFERRED_VERSION_gcc-8-cross = "8.5.0"
PREFERRED_VERSION_gcc-8-cross-aarch64 = "8.5.0"
PREFERRED_VERSION_gcc-8-cross-canadian = "8.5.0"
PREFERRED_VERSION_gcc-8-runtime = "8.5.0"
PREFERRED_VERSION_gcc-source = "8.5.0"
PREFERRED_VERSION_libgcc-8 = "8.5.0"
PREFERRED_VERSION_libgcc-8-initial = "8.5.0"

# Some Nvidia libraries (nvinfer) are compiled against newer version of libstdc++, requiring 6.0.30 at least (libstdc++.so.6.0.30) ()
# So add and use GCC 12.1 as minimun to support it (https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)
# Using a snapshot from gcc on https://github.com/openembedded/openembedded-core/tree/b8878cf0d35cf3d1ac30576d9b9943a7761c011b/meta/recipes-devtools/gcc
GCCVERSION = "12.%"

# We want to use all device trees so that the doflash.sh/tegra-flash-helper.sh can detect the SKU and flash the AGX Orin
# Without us having to customize it manually
KERNEL_DEVICETREE = "tegra234-p3737-0000+p3701-0000-nv.dtb tegra234-p3737-0000+p3701-0004-nv.dtb tegra234-p3737-0000+p3701-0005-nv.dtb"
