BANNER[nvidia-orin] = "The nvidia-orin layer includes NVIDIA proprietary licenses, where additional third party licenses may apply. Please consult your legal department should you have questions regarding the licensing terms and obligations."

RECIPE_LIST_LAYERS:remove = "wr-nvidia-orin"

# Recipe Enablement
WRL_RECIPES:openembedded-layer += "canutils"
WRL_RECIPES:openembedded-layer += "glmark2"
WRL_RECIPES:tegra += "libglvnd-tegra \
    cuda-command-line-tools \
    cuda-compatibility-workarounds \
    cuda-compiler \
    cuda-environment \
    cuda-libraries \
    cuda-samples \
    cuda-target-environment \
    cuda-toolkit \
    egl-gbm \
    egl-wayland \
    eglexternalplatform \
    gcc \
    gstreamer1.0-plugins-nvdrmvideosink \
    gstreamer1.0-plugins-nveglgles \
    gstreamer1.0-plugins-nvjpeg \
    gstreamer1.0-plugins-nvtee \
    gstreamer1.0-plugins-tegra \
    l4t-launcher-extlinux \
    libconfig-tegra \
    libgcc \
    libusbgx-tegra-initrd-flash \
    nvgstapps \
    nvidia-drm-loadconf \
    nvidia-kernel-oot \
    packagegroup-cuda-sdk-host \
    setup-nv-boot-control \
    tar-l4t-workaround \
    tegra-argus-daemon \
    tegra-bluetooth \
    tegra-cmake-overrides \
    tegra-drm-headers \
    tegra-eeprom-tool \
    tegra-eks-image \
    tegra-espimage \
    tegra-flash-init \
    tegra-flash-reboot \
    tegra-flashvars \
    tegra-helper-scripts \
    tegra-initrd-flash-initramfs \
    tegra-minimal-init \
    tegra-minimal-initramfs \
    tegra-nvphs \
    tegra-nvpmodel \
    tegra-nvs-service \
    tegra-nvsciipc \
    tegra-nvstartup \
    tegra-redundant-boot \
    tegra-storage-layout \
    tegra-wifi \
    tos-optee \
"
