BUILD_NVIDIA_PROPRIETARY_PACKAGE ?= "0"
DISTRO_FEATURES:append = " ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
	'largefile opengl ptest multiarch wayland vulkan \
	systemd pam virtualization usrmerge', '', d)}"
IMAGE_FEATURES:append = " ${@bb.utils.contains('BUILD_NVIDIA_PROPRIETARY_PACKAGE', '1', \
	'hwcodecs', '', d)}"
PREFERRED_VERSION_optee-client ?= "%-l4t-%"
