BANNER[nvidia-orin] = "The nvidia-orin layer includes NVIDIA proprietary licenses, where additional third party licenses may apply. Please consult your legal department should you have questions regarding the licensing terms and obligations."

RECIPE_LIST_LAYERS:remove = "wr-nvidia-orin"

# Recipe Enablement
WRL_RECIPES:openembedded-layer += "canutils"
WRL_RECIPES:openembedded-layer += "glmark2"
WRL_RECIPES:tegra += "libglvnd-tegra \
	egl-wayland \
	egl-gbm \
	eglexternalplatform \
	cuda-samples \
	libusbgx-tegra-initrd-flash \
	libgcc \
	gcc \
	nvidia-kernel-oot \
	gstreamer1.0-plugins-nvdrmvideosink \
	gstreamer1.0-plugins-nveglgles \
	gstreamer1.0-plugins-nvjpeg \
	gstreamer1.0-plugins-nvtee \
	nvgstapps \
"
