BBPATH .= ":${LAYERDIR}"
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "wr-nvidia-orin"
BBFILE_PATTERN_wr-nvidia-orin = "^${LAYERDIR}/"
BBFILE_PRIORITY_wr-nvidia-orin = "5"

LAYERVERSION_wr-nvidia-orin = "1"

LAYERDEPENDS_wr-nvidia-orin = "core tegra"

LAYERSERIES_COMPAT_wr-nvidia-orin = "kirkstone wrl"

LAYER_PATH_wr-nvidia-orin = "${LAYERDIR}"
