#
# Copyright (C) 2025 Wind River Systems, Inc.
#

# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend \
	${LAYERDIR}/classes/*.bbclass"

BBFILE_COLLECTIONS += "wr-nvidia-orin"
BBFILE_PATTERN_wr-nvidia-orin := "^${LAYERDIR}/"
BBFILE_PRIORITY_wr-nvidia-orin = "7"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_wr-nvidia-orin = "1"

LAYERSERIES_COMPAT_wr-nvidia-orin = "wrl walnascar"
LAYERDEPENDS_wr-nvidia-orin = "core wrlinux tegra tegra-community"
