BBPATH .= ":${LAYERDIR}"

BBFILES += "${@bb.utils.contains_any('MACHINE', 'nvidia-orin', '${LAYERDIR}/recipes-*/*/*.bb', '', d)}"
BBFILES += "${@bb.utils.contains_any('MACHINE', 'nvidia-orin', '${LAYERDIR}/recipes-*/*/*.bbappend', '', d)}"

BBFILE_PATTERN_IGNORE_EMPTY_wr-nvidia-orin = "1"

BBFILE_COLLECTIONS += "wr-nvidia-orin"
BBFILE_PATTERN_wr-nvidia-orin = "^${LAYERDIR}/"
BBFILE_PRIORITY_wr-nvidia-orin = "5"

LAYERVERSION_wr-nvidia-orin = "1"

LAYERDEPENDS_wr-nvidia-orin = "core tegra"

LAYERSERIES_COMPAT_wr-nvidia-orin = "scarthgap wrl"

LAYER_PATH_wr-nvidia-orin = "${LAYERDIR}"
